[build]
  command = "npm run build"
  functions = "functions/lib"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
