// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-dvh overflow-hidden">
      {" "}
      {/* ✅ bloquea scroll global */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-dvh overflow-hidden`}
      >
        {/* 🔹 Fondo de madera */}
        {/* <div
          className="fixed inset-0 -z-10 bg-cover bg-center"
          style={{ backgroundImage: "url('/images/frame.jpg')" }}
        /> */}

        {/* Contenido */}
        <div className="h-dvh w-full flex items-center justify-center p-0 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
